### ISSUE TITLE
Deprecated selector in `apex-syntax/index.less`

### ISSUE THREAD

**Issue by bdubaut** [apex/apex-syntax#3]
In `apex-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .lines .cursor-line,
:host .lines .cursor-line` => `atom-text-editor .lines .cursor-line,atom-text-editor .lines .cursor-line`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `.string` => `.syntax--string`

* `.comment` => `.syntax--comment`

* `.punctuation.definition.comment` => `.syntax--punctuation.syntax--definition.syntax--comment`

* `.punctuation.definition.bold` => `.syntax--punctuation.syntax--definition.syntax--bold`

* `.punctuation.definition.italic` => `.syntax--punctuation.syntax--definition.syntax--italic`

* `.punctuation.section.embedded` => `.syntax--punctuation.syntax--section.syntax--embedded`

* `.source.css .selector` => `.syntax--source.syntax--css .syntax--selector`

* `.source.css .property-value` => `.syntax--source.syntax--css .syntax--property-value`

* `.source.gfm .heading.marker` => `.syntax--source.syntax--gfm .syntax--heading.syntax--marker`

* `.source.gfm .heading` => `.syntax--source.syntax--gfm .syntax--heading`

* `.todo,
.fixme,
.xxx` => `.syntax--todo,
.syntax--fixme,
.xxx`

* `atom-text-editor::shadow .bracket-matcher .region` => `atom-text-editor.editor .bracket-matcher .region`

* `.tab-bar .tab[data-type="TextEditor"]::after` => `.tab-bar .syntax--tab[data-type="TextEditor"]::after`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by AyushKenhi** [comment]
Why is this open yet. Its all fixed

**Comment by bdubaut** [comment]
@AyushKenhi ¯\_(ツ)_/¯

**Comment by CraigDamlo** [comment]
I'm still getting this error, with all added packages disabled.

**Comment by AyushKenhi** [comment]
@CraigDamlo Am pretty sure there are no deprecated selectors on this package. Are you sure those Depractions are of Apex **Syntax** only and not of Apex **UI**  and have you updated all of your packages

**Comment by saadq** [comment]
I'm still getting this issue as well when you install with `apm install apex-syntax`. I believe the published version needs to be updated with the latest changes on `apm`.

**Comment by dpo** [comment]
Still getting those deprecation errors too.

**Comment by tj** [comment]
ah sorry I didn't publish, v0.2.0
